# Generated by Django 4.2.11 on 2024-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
