# Generated by Django 4.2.11 on 2024-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_ingredient_calo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
