# Generated by Django 4.2.11 on 2024-04-29 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
